/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airline;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
//import com.sun.jdi.connect.spi.Connection;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class ManagePassengers extends javax.swing.JFrame {

    /**
     * Creates new form ManagePassengers
     */
    public ManagePassengers() {
        initComponents();
        DisplayPassengers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Pnametb = new javax.swing.JTextField();
        Passnumtb = new javax.swing.JTextField();
        Gendercombobox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Passengertable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        Nationtb = new javax.swing.JTextField();
        Phonenumtb = new javax.swing.JTextField();
        Addresstb = new javax.swing.JTextField();
        Editbutton = new javax.swing.JButton();
        Savebutton = new javax.swing.JButton();
        Backbutton = new javax.swing.JButton();
        Deletebutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 10));

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Java Project\\logooo.jpg")); // NOI18N
        jLabel2.setText("Aaha Airlines");

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Manage Passengers");

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Passport Number");

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Passenger Name");

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Phone Number");

        jLabel6.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Gender");

        jLabel7.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Address");

        Pnametb.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        Pnametb.setForeground(new java.awt.Color(0, 0, 153));

        Passnumtb.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        Passnumtb.setForeground(new java.awt.Color(0, 0, 153));

        Gendercombobox.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        Gendercombobox.setForeground(new java.awt.Color(0, 0, 153));
        Gendercombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male", "Others" }));

        jLabel8.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Passengers List");

        Passengertable.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        Passengertable.setForeground(new java.awt.Color(0, 0, 153));
        Passengertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "PID", "PName", "PNat", "PGen", "PPass", "PAdd", "Pphone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Passengertable.setSelectionForeground(new java.awt.Color(0, 204, 255));
        Passengertable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PassengertableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Passengertable);
        Passengertable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jLabel9.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Nationality");

        Nationtb.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        Nationtb.setForeground(new java.awt.Color(0, 0, 153));

        Phonenumtb.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        Phonenumtb.setForeground(new java.awt.Color(0, 0, 153));

        Addresstb.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        Addresstb.setForeground(new java.awt.Color(0, 0, 153));

        Editbutton.setBackground(new java.awt.Color(0, 0, 153));
        Editbutton.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        Editbutton.setForeground(new java.awt.Color(255, 255, 255));
        Editbutton.setText("Edit");
        Editbutton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 153, 255)));
        Editbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditbuttonMouseClicked(evt);
            }
        });

        Savebutton.setBackground(new java.awt.Color(0, 0, 153));
        Savebutton.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        Savebutton.setForeground(new java.awt.Color(255, 255, 255));
        Savebutton.setText("Save");
        Savebutton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 153, 255)));
        Savebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SavebuttonMouseClicked(evt);
            }
        });
        Savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavebuttonActionPerformed(evt);
            }
        });

        Backbutton.setBackground(new java.awt.Color(0, 0, 153));
        Backbutton.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        Backbutton.setForeground(new java.awt.Color(255, 255, 255));
        Backbutton.setText("Back");
        Backbutton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 153, 255)));
        Backbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackbuttonMouseClicked(evt);
            }
        });
        Backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbuttonActionPerformed(evt);
            }
        });

        Deletebutton.setBackground(new java.awt.Color(0, 0, 153));
        Deletebutton.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        Deletebutton.setForeground(new java.awt.Color(255, 255, 255));
        Deletebutton.setText("Delete");
        Deletebutton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 153, 255)));
        Deletebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeletebuttonMouseClicked(evt);
            }
        });
        Deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Pnametb, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(117, 117, 117)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(125, 125, 125)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel7)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(Savebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138)
                        .addComponent(Editbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143)
                        .addComponent(Deletebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(604, 604, 604)
                                .addComponent(jLabel1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(675, 675, 675)
                                .addComponent(jLabel8))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(385, 385, 385)
                                .addComponent(Nationtb, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addComponent(Gendercombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(110, 110, 110)
                                        .addComponent(Passnumtb, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(68, 68, 68)
                                        .addComponent(Addresstb, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(23, 23, 23)))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(Phonenumtb, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(452, 452, 452))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gendercombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pnametb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nationtb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Passnumtb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Phonenumtb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Addresstb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Editbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Deletebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Savebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel8)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SavebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SavebuttonActionPerformed

    private void BackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackbuttonActionPerformed

    private void BackbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackbuttonMouseClicked
        new MainPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackbuttonMouseClicked

Connection con=null;
Statement st=null,st1=null;
ResultSet rs=null,rs1=null;
private void  DisplayPassengers()
{try{
    Class.forName("com.mysql.cj.jdbc.Driver");
    con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/airline?zeroDateTimeBehavior=CONVERT_TO_NULL","root","root");
    st=con.createStatement();
    rs=st.executeQuery("select * from passengerstbl");
    DefaultTableModel tm=new DefaultTableModel();
    tm.setColumnIdentifiers(new Object[]{"Pid","PName","PNat","PGen","PPass","PAdd","Pphone"});
    while(rs.next())
    {
        tm.addRow(new Object[]{
        rs.getString("Pid"),
            rs.getString("PName"),
            rs.getString("PNat"),
            rs.getString("PGen"),
            rs.getString("PPass"),
            rs.getString("PAdd"),
            rs.getString("Pphone")
        });
    }
    Passengertable.setModel(tm);
    
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(this,e);
}
    
}
int passid=0;
private void countpass(){
    try{
        st1=con.createStatement();
        rs1=st1.executeQuery("select Max(PId) from passengerstbl");
        rs1.next();
        passid=rs1.getInt(1)+1;
        
    }
    catch(Exception e)
    {
        
    }
}
private void clear(){
    Pnametb.setText("");
     Nationtb.setText("");
     Passnumtb.setText(""); 
     Phonenumtb.setText(""); 
     Addresstb.setText("");
        
}
    private void SavebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SavebuttonMouseClicked
        if(Pnametb.getText().isEmpty()|| Passnumtb.getText().isEmpty()|| Addresstb.getText().isEmpty()||Phonenumtb.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Missing Information");
        }
        else
        {
          try{
              countpass();
              Class.forName("com.mysql.cj.jdbc.Driver");
              con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/airline?zeroDateTimeBehavior=CONVERT_TO_NULL","root","root");
             PreparedStatement Add=null;
             Add = con.prepareStatement("insert into passengerstbl (Pid,PName,PNat,PGen,PPass,PAdd,Pphone)values(?,?,?,?,?,?,?)");
              Add.setInt(1,passid);
              Add.setString(2,Pnametb.getText());
              Add.setString(3,Nationtb.getText());
              Add.setString(4,Gendercombobox.getSelectedItem().toString());
              Add.setString(5,Passnumtb.getText());
              Add.setString(6,Addresstb.getText());
              Add.setString(7,Phonenumtb.getText());
              int row=Add.executeUpdate();
              JOptionPane.showMessageDialog(this,"Passenger Added");
              con.close();
              DisplayPassengers();
              clear();
          }  
          catch(Exception e)
          {
              JOptionPane.showMessageDialog(this,e);
          }
        }
    }//GEN-LAST:event_SavebuttonMouseClicked

    private void DeletebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletebuttonMouseClicked
        // TODO add your handling code here:
        if(key==0)
        {
            JOptionPane.showMessageDialog(this,"Select a passenger");
        }
        else
        {
            try{
                con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/airline?zeroDateTimeBehavior=CONVERT_TO_NULL","root","root");
                String query="Delete from passengerstbl where PId="+key;
                Statement del=con.createStatement();
                del.executeUpdate(query);
                JOptionPane.showMessageDialog(this, "Passenger Deleted");
                DisplayPassengers();
                clear();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this,e);
            }
        }
    }//GEN-LAST:event_DeletebuttonMouseClicked
int key=0;

    private void PassengertableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassengertableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel mo=(DefaultTableModel)Passengertable.getModel();
        int index=Passengertable.getSelectedRow();
        key=Integer.valueOf(mo.getValueAt(index,0).toString());
        Pnametb.setText(mo.getValueAt(index, 1).toString());
        Nationtb.setText(mo.getValueAt(index, 2).toString());
        Passnumtb.setText(mo.getValueAt(index, 4).toString());
        Addresstb.setText(mo.getValueAt(index, 5).toString());
        Phonenumtb.setText(mo.getValueAt(index, 6).toString());
        Gendercombobox.setSelectedItem(mo.getValueAt(index, 3).toString());
    }//GEN-LAST:event_PassengertableMouseClicked

    private void DeletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeletebuttonActionPerformed

    private void EditbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditbuttonMouseClicked
        // TODO add your handling code here:
        if(key==0)
        {
            JOptionPane.showMessageDialog(this,"Select a Passenger");
        }
        else
        {
            try{
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airline?zeroDateTimeBehavior=CONVERT_TO_NULL","root","root");
                String Query = "UPDATE passengerstbl SET PName=?, PNat=?, PGen=?, PPass=?, PAdd=?, Pphone=? WHERE Pid=?";
                PreparedStatement Add = con.prepareStatement(Query);
                Add.setInt(7,key);
                Add.setString(1,Pnametb.getText());
                Add.setString(2,Nationtb.getText());
                Add.setString(3,Gendercombobox.getSelectedItem().toString());
                Add.setString(4,Passnumtb.getText());
                Add.setString(6,Phonenumtb.getText());
                Add.setString(5,Addresstb.getText());
                int row=Add.executeUpdate();
                JOptionPane.showMessageDialog(this,"Passenger updated");
                con.close();
                DisplayPassengers();
                clear();
            }
            catch(Exception e)
            {
                 JOptionPane.showMessageDialog(this,e);
            }
        }
    }//GEN-LAST:event_EditbuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagePassengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagePassengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagePassengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagePassengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagePassengers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Addresstb;
    private javax.swing.JButton Backbutton;
    private javax.swing.JButton Deletebutton;
    private javax.swing.JButton Editbutton;
    private javax.swing.JComboBox<String> Gendercombobox;
    private javax.swing.JTextField Nationtb;
    private javax.swing.JTable Passengertable;
    private javax.swing.JTextField Passnumtb;
    private javax.swing.JTextField Phonenumtb;
    private javax.swing.JTextField Pnametb;
    private javax.swing.JButton Savebutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
